### ISSUE TITLE
Script does not compile luceneserver sources

### ISSUE THREAD

**Issue by leoperezpulido** [mikemccand/luceneserver#3]
Calling build.py package successfully clone lucene6x branch. Then, the call to compileLuceneModules() also successfully compile 92 sources. After it returns there is a call to:

jarFileName = 'build/luceneserver-%s.jar' % jarVersion.

But there seems not to exist these luceneserver-<VERSION>.jar file at these moment.

Here is the traceback:
Traceback (most recent call last):
  File "./build.py", line 701, in <module> main()
  File "./build.py", line 511, in main jarFileName = compileSourcesAndDeps(jarVersion)
  File "./build.py", line 443, in compileSourcesAndDeps compileChangedSources('src/java', 'build/classes/java', l)
  File "./build.py", line 370, in compileChangedSources run(' '.join(cmd))
  File "./build.py", line 310, in run raise RuntimeError('command "%s" failed' % s)
RuntimeError: command "javac -Xmaxerrs 10000 -d build/classes/java -cp lib/jackson-core-2.8.2.jar:lib/commons-codec-1

Using Lubuntu 17-04.

**Comment by leoperezpulido** [comment]
- The main problem is that the code that clone the branch download a 6.7.0-SNAPSHOT version.
- Then, I change the code to reflect the new downloaded branch to LUCENE_VERSION = '6.7.0-SNAPSHOT', and the build fail asking for two classes:

org.apache.lucene.search.join.ToParentBlockJoinIndexSearcher, and
org.apache.lucene.search.join.ToParentBlockJoinCollector.

which were removed in Lucene 6.5.0

* LUCENE-6959: Removed ToParentBlockJoinCollector in favour of
  ParentChildrenBlockJoinQuery, that can return the matching children documents per
  parent document. This query should be executed for each matching parent document
  after the main query has been executed. (Adrien Grand, Martijn van Groningen,
  Mike McCandless)

- Then, I clone and compile with a 6.4.3 version, and build failed again:

[Lucene-Server_Build-6.4.3.txt](https://github.com/mikemccand/luceneserver/files/1236795/Lucene-Server_Build-6.4.3.txt)

**Comment by leoperezpulido** [comment]
**Issue solved**... (at least temporarily)

The main problem was that build.py clone a 6.7.0-SNAPSHOT branch.  

If you change the the code in the script to reflect this change, say LUCENE_VERSION = '6.7.0-SNAPSHOT', the build fail again asking for two classes:

org.apache.lucene.search.join.ToParentBlockJoinIndexSearcher, and
org.apache.lucene.search.join.ToParentBlockJoinCollector

which were removed in Lucene 6.5.0
* LUCENE-6959: Removed ToParentBlockJoinCollector in favour of
  ParentChildrenBlockJoinQuery, that can return the matching children documents per
  parent document. This query should be executed for each matching parent document
  after the main query has been executed. (Adrien Grand, Martijn van Groningen,
  Mike McCandless)

You can clone a 6.4.x branch, but the build fail again asking FieldDefBindings to override abstract method getDoubleValuesSource(String) in Bindings, which is declared in version 6.7.0-SNAPSHOT.

But FieldDefBindings override ValueSource getValueSource(String), which was removed in 6.4.0:
* LUCENE-7609: The expressions module now uses the DoubleValuesSource API, and 
  no longer depends on the queries module.  Expression#getValueSource() is
  replaced with Expression#getDoubleValuesSource(). (Alan Woodward, Adrien
  Grand)

Next, let's try and clone branch_6_3, but build fails again with one error: writer is not public in PrimaryNode; cannot be accessed from outside package, which was made protected:
* make PrimaryNode's IndexWriter protected
mikemccand committed on Nov 18, 2016 - 1 parent 6d540b9 commit 5e062d209aa87dd26406a098cca1159e00d11bd4.

Then I edit IndexWriter in PrimaryMode (not a good choice, but meanwhile a study the code to make a patch) to made it public and the server compiles and run successfully.

build lucene core JAR...
build lucene analyzers-common JAR...
build lucene analyzers-icu JAR...
build lucene facet JAR...
build lucene codecs JAR...
build lucene grouping JAR...
build lucene highlighter JAR...
build lucene misc JAR...
build lucene suggest JAR...
build lucene replicator JAR...
compile 85 sources
build build/luceneserver-0.1.1-SNAPSHOT.jar
fatal: Not a git repository (or any of the parent directories): .git
fatal: Not a git repository (or any of the parent directories): .git
Wrote build/luceneserver-0.1.1-SNAPSHOT.zip (20.5 MB)

Thank Mike!
